language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

virtualenv:
  system_site_packages: true

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" ODOO_LINT="0"

  matrix:
  - LINT_CHECK=1 ODOO_LINT=1
  - ODOO_REPO="vauxoo/odoo" TESTS=1

install:
  - git clone --single-branch --depth=1 https://github.com/OCA/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success

